<?php

function generatePlaceholderBio() {
  $name = trim(get_the_title());
  $bioArray = [];

  $noun = array("factory reset button","big idiot","toaster","legend","therapist","psychic","knife","sandwich","lettuce","kitty","friendly grandma","french chef","bag of drugs","corn cake","boy mayor of secondlife","candlestick maker","coffee pot","tank","broken bra","skinny woman","private investor","stock car","terrible rock band","blood splatter","telephone","mad cow","rough-skinned newt","karate master","pistol","legal warrant","injured person","party","place of business","puppy","famous landscape painting","pair of hairy legs","decrepit Irish cottage","pocket flask","canister of liquid oxygen","laser beam","dingle berry","cuddle party","mess","trust fund","volcanic crater","travel guidebook","furnace","police squad","rabid dog","sneaky criminal","keepsake machete","gaming laptop","dog poop","dragon","mediation","patrolman","pervert","toilet seat","haunted graveyard","really tough guy","twinkling diamond","wrinkle","multi-billionaire","sweet tailpipe","pot of boiling water","deer antler","background story","mood","nibblet","striped hyena","weed whacker");
  
  $adjective = array("hysterical","spidery","sleepless","fractured","benighted","proven","barbed","sacrificed","disreputable","rancid","unspoken","stunned","immobilized","querulous","murdering","congratulating","deprived","foreign","filthy","spitfire","primitive","craggy","disobeyed","unintelligible","embarrassed","waving","rotting","oak","unseeing","loyal","vile","dour","swelling","flexible","bloodless","splashed","sketched","emblazoned","infant","studded","barren","screeching","emerging","drafty","flaming","flooded","pathless","absent","drowsy","gripping","engrossed","shaky","deadly","hairless","sadistic","metallic","wild","domesticated","medicated","cocky","massive","disrespectful","hilarious","sexy","hot","very tactful","bearded","duck-like","violent","slimy","self-centered","talking","naked","angry","shaky","deep","sick","zippy","sticky","fluffy","frozen","painfully honest","filthy","fighting","frisky","greedy","hideous","drunken","hateful","twisted","useless","magical","godawful","confused","flirting","high-end","maniacal","sickened","slippery","stubborn","tripping","vengeful","sinister","costumed","cowardly","haunting","startled","demanding","shivering","offensive","nighttime","startling","disgusting","slap happy","disturbing","blathering","flickering","rebellious","bull headed","hyperactive","pea-brained","territorial","underhanded","zombie-like","mischievous","free-loading","house-broken","cruel-hearted","misunderstood","narrow-minded","self-absorbed","bat-shit-crazy","fiercely-loyal");
  
  $verb = array("surround","stab","return","medicate","blindside","boogie","flap","trip","swat","suck in","harass","trap","snoop","explode","sketchy","scatter","challenge","fight","bury","splatter","smack","kill");
  
  $adverb = array("accidentally","angrily","annually","anxiously","awkwardly","badly","blindly","boastfully","boldly","bravely","briefly","brightly","busily","calmly","carefully","carelessly","cautiously","cheerfully","clearly","correctly","courageously","crossly","cruelly","daily","defiantly","deliberately","doubtfully","easily","elegantly","enormously","enthusiastically","equally","eventually","exactly","faithfully","fatally","fiercely","fondly","foolishly","fortunately","frantically","gently","gladly","gracefully","greedily","happily","hastily","honestly","hourly","hungrily","innocently","inquisitively","irritably","joyously","justly","kindly","lazily","loosely","loudly","madly","merrily","monthly","mortally","mysteriously","nearly","neatly","nervously","never","noisily","obediently","obnoxiously","often","painfully","perfectly","politely","poorly","powerfully","promptly","punctually","quickly","quietly","rapidly","rarely","really","recklessly","regularly","reluctantly","repeatedly","rightfully","roughly","rudely","sadly","safely","seldom","selfishly","seriously","shakily","sharply","shrilly","shyly","silently","sleepily","slowly","smoothly","softly","solemnly","sometimes","soon","speedily","stealthily","sternly","successfully","suddenly","suspiciously","swiftly","tenderly","tensely","thoughtfully","tightly","tomorrow","truthfully","unexpectedly","victoriously","violently","vivaciously","warmly","weakly","wearily","wildly","yearly","nakedly","laughingly","obnoxiously","irritatingly","underhandedly");

  shuffle($noun);
  shuffle($adjective);
  shuffle($verb);
  shuffle($adverb);

  array_push($bioArray,"<h3>Wanted by the FBI: $name</h3><p>The FBI is offering a reward of up to $" . mt_rand(1,50) .",000 for information that leads to the identification, arrest, and conviction of internet commentator $name.</p><h3>Remarks:</h3><p>$name has the following tattoos: a $noun[0] on their lower back; a $noun[1] atop a $noun[2] on their right ankle; and a photo-realistic image of a $noun[3] on their forehead.</p><h3>Details:</h3><p>$name is wanted for the armed robbery of an adult novelty toy location. They were recorded on camera $adverb[0] attacking the store clerk with a $noun[4]. After the assault, they ransacked the store and ran off, stealing an estimated $".mt_rand(4,9)."000 worth of used Bad Dragon toys. A second security camera spotted $name two blocks down the road, handing the blood-splattered $noun[4] to a confused homeless person. If you see $name, call our hotline immediately. Do not attempt to apprehend this suspect on your own, as witnesses have described $name to be as “$adjective[0], $adjective[1], and a terrible dresser to boot.”</p>");

  array_push($bioArray,"<h3>$name's self-summary</h3><p>$name is a gorgeous ".mt_rand(1,9)." foot ".mt_rand(1,11)." inch tall individual who could easily pass as a human being. They have long, $adjective[0] hair the color of a $noun[0], and $adjective[1] eyes. They are currently on the prowl for a lucky partner to date, $verb[0], and fuck (in that order).</p><h3>What $name is doing with their life</h3><p>$name runs a succesful $noun[1] harvesting farm. The process is a trade secret, but the results clearly speak for themselves. Every day, $name selects the most $adjective[2] $noun[1], and loads up the back seat of their car with the prized harvet. They then sell the $noun[1] at a local market, which fetches a pretty penny.</p><p>$name also is part of a comedy podcast</p><h3>$name is really good at</h3><p>Having an orgasm face that looks $adverb[0] sexy.</p><h3>$name spends a lot of time thinking about</h3><p>The legality of their business, and what to do when a $noun[1] turns out to be more $adjective[3] than $adjective[2]. </p><h3>You should message $name if</h3><p>You'd like to give them a hand with their work, and perhaps a <em>hand</em> when the two of you are done working, if you know what I mean. $name would also like to hear from you if you've recently passed your bar exam, or if you're looking to make money without asking too many questions.</p>");

  array_push($bioArray,"<h4>iUniverse Publishing presents…</h4><h3>The Taming of the <span style='text-transform:capitalize'>$adjective[0] $noun[0]</span>, by $name</h3><p>”My dear $name! You’ll never know how much I truly love you!” said the <span style='text-transform:capitalize'>$noun[0]</span></p><p>“As do I” $name replied $adverb[0]. “Alas, our love was not meant to be. After all, you are to be wed to the <span style='text-transform:capitalize'>great duke $noun[1]</span> of Canterbury in the morning!”</p><p>“But he is not a world-renown podcast member like you are!” the <span style='text-transform:capitalize'>$noun[0]</span> cried aloud. “Compared to you, <span style='text-transform:capitalize'>$noun[1]</span> is like a $adjective[1] $noun[3].” The <span style='text-transform:capitalize'>$noun[0]</span> then spat upon the floor, as to prove her point.</p><p>“Oh, my dear $adjective[0] <span style='text-transform:capitalize'>$noun[0]</span>, I know all too well what you mean. But that is simply how the world turns. Unless…” $name[0] paused for a moment to think. “No, that would not be the proper Victorian thing to do...”</p><p>“What is it $name, my love?” the <span style='text-transform:capitalize'>$noun[0]</span> inquired. $name stared back at her, then broke into a smile. “Unless we elope my love. Come with me, let us run into the night, and make $adjective[2] love under the moonlight! Maybe we can even do that thing again where you take that $noun[4] and shove it up-”</p><p>At that very moment, the bedroom door slammed open, shocking the two lovers. “I’m afraid that won’t be happening,” <span style='text-transform:capitalize'>great duke $noun[1]</span> growled, leaning against the door frame. “For tomorrow, after the wedding, <span style='text-transform:capitalize'>$noun[0]</span> will be $adjective[0] no longer. As for you, $name, you will be hanged for your adulterous crimes!”</p><hr /><h4>Purchase a copy of The Taming of the <span style='text-transform:capitalize'>$adjective[0] $noun[0]</span> to find out what happens next!</h4><p>$15.99 Paperback <button>Sold out!</button></p><p>$13.99 Digital <button>Sold out!</button></p>");

  array_push($bioArray,"<h3>$name – Dirty Shower Time with a <span style='text-transform:capitalize'>$noun[0]</span></h3><p>$name is feeling very dirty after a long, hard day of recording for Extra Credit, and is in need of a help of a $noun[0] to clean up! Watch as $name runs the $noun[0] across their legs, while making sexy, $adjective[0] motions at the camera. Oh,  it looks like you’ve been invited to join into the washing fun, but will the two of you actually get clean? </p><p>Then, a cameraman starts to get a little woozy from all the hot action, and decides to join in. He $adverb[0] launches into the action, bringing a $noun[1] with him to spice up the scene. But it looks like you and $name aren’t a fan of his $noun[1] interfering with the $adjective[1] erotic $noun[0], so the two of you knock him out and proceed to murder him! Witness the world’s first erotic, point-of-view, murder simulation. Watch as $name and you commit the act, hide the body, then finish off an erotic assisted-masturbation scene right atop the shallow grave! And to finish it all off, $name will return to the shower where it all began and whip out the $noun[0] for one last bit of fun!</p><hr /><p>Category: $noun[0]<br/>Related Categories: Shower, $noun[0], POV, Snuff<br/>Keywords: $noun[0], give me money, a murder most foul, totally not real dont call the police. $noun[1]<br/>Price: $30.99<br/>Format: AVI, MP4, FLAC, WAV, TXT<br/>Length: ".mt_rand(10,50)." minutes ".mt_rand(10,59)." seconds<br/>Resolution: 800x400<br/>Size: 2Gb<br/>Added April 1st, 2017</p>");

  array_push($bioArray,"<h3>wikiHow To Cure Your Crippling Addiction to $name</h3>We’ve all had moments of weakness, where we can’t help but fall in love with $name"."’s"." voice. It’s a natural part of life, and only shows that you are human. However, some people may not want to be addicted to the $adjective[0] quality of $name"."’s"." voice, so here are a few steps you can follow to break free.<h4 style='text-transform:capitalize'>Method 1: Realize there’s nothing wrong with your addiction</h4><p>Step 1: <strong>It’s okay to love listening to $name"."’s"." voice.</strong> It’s really fine. Just make sure you limit your activities to just listening.</p><p>Step 2: <strong>Consider why you want to stop being addicted.</strong> Are your parents making you stop? Would they rather you take up their boring family tradition of knitting a yarn $noun[0] every night next to the fireplace? Explain to them that you can knit while listening to $name’s podcast. </p><h4 style='text-transform:capitalize'>Method 2: Stop listening to $name</h4><p>Step 1: <strong>Try to find an episode that $name is in, but where $name isn’t actively participating or being funny.</strong> It’s Extra Credit after all, so there’s bound to be at least a dozen episodes where that’s bound to be the case.</p><p>Step 2: <strong>Move on to episodes where $name is not listed in the credits.</strong> It’ll feel like you’re about to hear $name"."’s"." voice at any moment, and the anticipation might put you in a $adjective[2] state of mind, but the best way out is through.</p><p>Step 3: <strong>It’s okay to relapse.</strong> You may find yourself missing that $adjective[0] voice, and those $adjective[3] tones of $name’s voice. If you find this process too hard, just $adverb[0] put on an episode in which $name is in, and take a few days before you try again.</p><p>Step 4: <strong>Listen to $name’s voice repeatedly.</strong> Sometimes the best way to stop smoking is to smoke a whole carton in one sitting, to the point where you grow sick of it. In that same vein, find a few of $name"."’s"." episodes, cut out all the other voices and the music, and put the results on loop. Make sure to listen carefully to how $name occasionally mispronounces a word or flubs a really easy joke setup. Eventually you may find you will grow tired of listening!</p><h3>Tips</h3><ul><li>Try switching to a more lossy audio format, to see if the lower quality helps break your addiction.</li><li>Make sure you really want to break your addiction before you begin. You may actually be fine, and it’s everyone around you that really has a problem</li></ul><h3>Warnings</h3><ul><li><strong>Be careful listening to too much of $name"."’s"." voice in one session!</strong> You could easily overdose, or cause serious damage to your ears. If you’re going to listen like this, then at the very least don’t listen alone! Always have a friend nearby whose not partaking, and who is able and willing to care for you</li></ul>");

  echo $bioArray[mt_rand(0,count($bioArray)-1)];
}